# Generated by Django 6.0.7 on 2026-08-04 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_curso_capa_upload_alter_curso_capa_url_externa'),
        ('pagamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrancaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_nsu', models.CharField(max_length=64, unique=True, verbose_name='número do pedido')),
                ('metodo', models.CharField(default='pix', max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('confirmado', models.BooleanField(default=False)),
                ('transaction_nsu', models.CharField(blank=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(blank=True, help_text='Vazio se o cliente ainda não tinha conta no momento do checkout.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas_externas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Cobrança externa',
                'verbose_name_plural': 'Cobranças externas',
            },
        ),
    ]
