# Generated by Django 6.0.7 on 2026-08-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_cobrancaexterna'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('mock', 'Modo teste (pagamento de enfeite, aprova tudo na hora)'), ('infinitepay', 'InfinitePay (pagamento real)')], default='mock', max_length=20)),
                ('infinitepay_handle', models.CharField(blank=True, help_text='Seu identificador no InfinitePay, sem o "$" (ex: gleison-pereira-z9a). Só é usado quando o gateway acima é InfinitePay.', max_length=100, verbose_name='InfiniteTag')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de pagamento',
                'verbose_name_plural': 'Configuração de pagamento',
            },
        ),
    ]
