# Generated by Django 4.2.30 on 2026-08-12 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_cupom'),
        ('pagamentos', '0004_cobrancaexterna_usa_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='cursos.cupom'),
        ),
    ]
