# Generated by Django 6.0.7 on 2026-07-10 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('descricao_curta', models.CharField(max_length=300, verbose_name='descrição curta (propaganda)')),
                ('descricao', models.TextField(verbose_name='descrição completa')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='cursos/capas/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MentoriaAoVivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data_hora', models.DateTimeField()),
                ('link_reuniao', models.URLField(blank=True, verbose_name='link da reunião (Meet/Zoom)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias', to='cursos.curso')),
            ],
            options={
                'ordering': ['data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('youtube_id', models.CharField(blank=True, max_length=20, verbose_name='ID do vídeo no YouTube')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='cursos/apostilas/', verbose_name='apostila em PDF')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='cursos.modulo')),
            ],
            options={
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
