# Generated by Django 6.0.7 on 2026-07-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_contatomensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='video_youtube_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='ID do vídeo de apresentação (YouTube)'),
        ),
    ]
