# Generated by Django 6.0.7 on 2026-07-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_curso_video_youtube_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='drive_file_id',
            field=models.CharField(blank=True, help_text='Preenchendo este campo, o vídeo é servido pelo Google Drive em vez do YouTube (sem marca/link do YouTube). Pegue o ID na URL de compartilhamento: drive.google.com/file/d/ESSE-TRECHO-AQUI/view — e desative a opção de download pra quem visualiza, nas configurações de compartilhamento do arquivo.', max_length=100, verbose_name='ID do arquivo no Google Drive'),
        ),
    ]
