# Generated by Django 6.0.7 on 2026-07-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_aula_drive_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleDriveConexao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField()),
                ('pasta_id', models.CharField(blank=True, max_length=100)),
                ('conta_email', models.EmailField(blank=True, max_length=254)),
                ('conectado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
