# Generated by Django 6.0.7 on 2026-07-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_googledriveconexao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoogleDriveConexao',
        ),
    ]
