# Generated by Django 6.0.7 on 2026-07-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_delete_googledriveconexao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='drive_pdf_file_id',
            field=models.CharField(blank=True, help_text='Alternativa ao upload local — preenchendo este campo, a apostila é servida direto do Google Drive (útil em hospedagem sem disco persistente, tipo Vercel). Mesmo esquema do vídeo: pega o ID em drive.google.com/file/d/ESSE-TRECHO-AQUI/view e desativa a opção de download pra quem visualiza.', max_length=100, verbose_name='ID da apostila no Google Drive'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cursos/apostilas/', verbose_name='apostila em PDF (upload local)'),
        ),
    ]
