# Generated by Django 6.0.7 on 2026-07-11 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0007_aula_drive_pdf_file_id_alter_aula_arquivo_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_titulo', models.CharField(default='Transforme sua carreira com nossos cursos', max_length=200)),
                ('hero_subtitulo', models.TextField(default='Aulas em vídeo, apostilas em PDF e mentoria ao vivo. Acesso liberado na hora, direto no navegador — no computador ou no celular.')),
                ('hero_video_youtube_id', models.CharField(blank=True, default='S9uPNppGsGo', max_length=20, verbose_name='ID do vídeo de apresentação (YouTube)')),
                ('sobre_texto', models.TextField(default='Somos uma plataforma de ensino online focada em resultado prático. Cada curso combina videoaulas, material de apoio em PDF e encontros de mentoria ao vivo com o instrutor.')),
                ('contato_email', models.EmailField(default='contato@saulocurso.local', max_length=254)),
                ('contato_telefone', models.CharField(default='(11) 90000-0000', max_length=20)),
                ('whatsapp_numero', models.CharField(default='5522998051490', help_text='Só números, com código do país e DDD (ex: 5522998051490).', max_length=20, verbose_name='Número do WhatsApp')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configurações do site',
            },
        ),
    ]
