# Generated by Django 6.0.7 on 2026-07-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0008_configuracaosite'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='hero_video_drive_file_id',
            field=models.CharField(blank=True, help_text='Alternativa ao YouTube — preenchendo este campo, o vídeo do hero é servido pelo Google Drive (tem prioridade sobre o YouTube). Cola o ID ou o link inteiro, extrai sozinho.', max_length=100, verbose_name='ID do vídeo de apresentação (Google Drive)'),
        ),
    ]
