# Generated by Django 6.0.7 on 2026-07-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0009_configuracaosite_hero_video_drive_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='drive_capa_file_id',
            field=models.CharField(blank=True, help_text='Alternativa ao upload local — preenchendo este campo, a capa é servida direto do Google Drive (útil em hospedagem sem disco persistente, tipo Vercel; tem prioridade sobre o upload). Pega o ID em drive.google.com/file/d/ESSE-TRECHO-AQUI/view — a imagem precisa estar compartilhada como "qualquer pessoa com o link".', max_length=100, verbose_name='ID da capa no Google Drive'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/capas/', verbose_name='capa (upload local)'),
        ),
    ]
