# Generated by Django 6.0.7 on 2026-07-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0010_curso_drive_capa_file_id_alter_curso_imagem_capa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='arquivo_pdf',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='imagem_capa',
        ),
        migrations.AlterField(
            model_name='aula',
            name='drive_pdf_file_id',
            field=models.CharField(blank=True, help_text='A apostila é servida direto do Google Drive. Mesmo esquema do vídeo: pega o ID em drive.google.com/file/d/ESSE-TRECHO-AQUI/view e desativa a opção de download pra quem visualiza.', max_length=100, verbose_name='ID da apostila no Google Drive'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='drive_capa_file_id',
            field=models.CharField(blank=True, help_text='Pega o ID em drive.google.com/file/d/ESSE-TRECHO-AQUI/view — a imagem precisa estar compartilhada como "qualquer pessoa com o link".', max_length=100, verbose_name='ID da capa no Google Drive'),
        ),
    ]
