# Generated by Django 6.0.7 on 2026-07-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0011_remove_aula_arquivo_pdf_remove_curso_imagem_capa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='capa_url_externa',
            field=models.URLField(blank=True, help_text='Alternativa ao Drive — cola o link direto da imagem (ex: termina em .jpg/.png). Se preencher os dois, o Drive tem prioridade.', verbose_name='URL da capa (link direto)'),
        ),
    ]
