# Generated by Django 6.0.7 on 2026-07-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0012_curso_capa_url_externa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID do vídeo no YouTube'),
        ),
        migrations.AlterField(
            model_name='configuracaosite',
            name='hero_video_youtube_id',
            field=models.CharField(blank=True, default='S9uPNppGsGo', max_length=200, verbose_name='ID do vídeo de apresentação (YouTube)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='video_youtube_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='ID do vídeo de apresentação (YouTube)'),
        ),
    ]
