# Generated by Django 6.0.7 on 2026-07-17 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0013_alter_aula_youtube_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaFrequente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=300)),
                ('resposta', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pergunta frequente',
                'verbose_name_plural': 'Perguntas frequentes',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='cnpj',
            field=models.CharField(blank=True, max_length=20, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='configuracaosite',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='link do Instagram'),
        ),
        migrations.AddField(
            model_name='contatomensagem',
            name='tipo',
            field=models.CharField(choices=[('contato', 'Contato geral'), ('empresa', 'Orçamento — Empresas')], default='contato', max_length=10),
        ),
        migrations.AddField(
            model_name='curso',
            name='carga_horaria',
            field=models.CharField(blank=True, help_text='Ex: 20 horas, 16h teóricas + 4h práticas.', max_length=50, verbose_name='carga horária'),
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidade',
            field=models.CharField(blank=True, choices=[('presencial', 'Presencial'), ('online', 'Online'), ('hibrido', 'Híbrido')], max_length=20),
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField(verbose_name='data de início')),
                ('local_ou_modalidade', models.CharField(blank=True, help_text="Ex: Presencial — Auditório RS Central, ou 'Online ao vivo'.", max_length=200, verbose_name='local ou modalidade')),
                ('vagas', models.PositiveIntegerField(blank=True, help_text='Deixe em branco pra não exibir vagas.', null=True)),
                ('observacao', models.CharField(blank=True, max_length=300)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cursos.curso')),
            ],
            options={
                'ordering': ['data_inicio'],
            },
        ),
    ]
