# Generated by Django 6.0.7 on 2026-08-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0014_perguntafrequente_configuracaosite_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='capa_upload',
            field=models.ImageField(blank=True, help_text='Envia o arquivo direto do computador. Se preencher o ID do Drive também, o Drive tem prioridade sobre esse upload.', null=True, upload_to='cursos/capas/', verbose_name='capa (upload direto)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='capa_url_externa',
            field=models.URLField(blank=True, help_text='Última opção — cola o link direto da imagem (ex: termina em .jpg/.png). Só é usada se não tiver Drive nem upload preenchido.', verbose_name='URL da capa (link direto)'),
        ),
    ]
