# Generated by Django 6.0.7 on 2026-08-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0015_curso_capa_upload_alter_curso_capa_url_externa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='capa_url_externa',
            field=models.CharField(blank=True, help_text='Última opção — cola o link direto da imagem (https://... ou um caminho relativo tipo /static/img/arquivo.jpg). Só é usada se não tiver Drive nem upload preenchido.', max_length=500, verbose_name='URL da capa (link direto)'),
        ),
    ]
