# Generated by Django 4.2.30 on 2026-08-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0016_alter_curso_capa_url_externa'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='informacoes_acesso',
            field=models.TextField(blank=True, help_text='Endereço, horário, o que levar etc. Só aparece pro aluno depois de ingressar (tela + email).', verbose_name='informações de acesso'),
        ),
        migrations.AddField(
            model_name='turma',
            name='link_grupo_whatsapp',
            field=models.URLField(blank=True, help_text='Só é mostrado/enviado ao aluno DEPOIS que ele ingressar na turma.', verbose_name='link do grupo do WhatsApp'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='observacao',
            field=models.CharField(blank=True, help_text='Aparece pro aluno matriculado junto do botão de ingressar (antes de ingressar).', max_length=300),
        ),
    ]
