# Generated by Django 4.2.30 on 2026-08-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_turma_informacoes_acesso_turma_link_grupo_whatsapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('percentual_desconto', models.DecimalField(decimal_places=2, help_text='Ex: 10 para 10%.', max_digits=5, verbose_name='% de desconto')),
                ('tipo', models.CharField(choices=[('automatico', 'Automático (desconta sozinho no preço)'), ('manual', 'Manual (aluno digita o código no checkout)')], max_length=20)),
                ('validade', models.DateField(verbose_name='válido até')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cursos', models.ManyToManyField(blank=True, related_name='cupons', to='cursos.curso', verbose_name='cursos onde vale')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
