# Generated by Django 4.2.30 on 2026-08-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0018_cupom'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='nome',
            field=models.CharField(blank=True, help_text='Ex: Turma Agosto/2026. Aparece pro aluno no botão de ingressar.', max_length=100, verbose_name='nome da turma'),
        ),
    ]
