# Generated by Django 6.0.7 on 2026-08-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0019_turma_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['ordem', '-criado_em']},
        ),
        migrations.AddField(
            model_name='curso',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Posição na home. Reordene arrastando em Ordenar cursos.'),
        ),
    ]
