# Generated by Django 6.0.7 on 2026-08-16 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0020_alter_curso_options_curso_ordem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mentoriaaovivo',
            name='alunos',
            field=models.ManyToManyField(blank=True, help_text="Só usado quando o público é 'Alunos específicos'.", related_name='mentorias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentoriaaovivo',
            name='publico',
            field=models.CharField(choices=[('todos', 'Todos os alunos do curso'), ('alunos', 'Alunos específicos'), ('turma', 'Uma turma inteira')], default='todos', max_length=10, verbose_name='quem vê a mentoria'),
        ),
        migrations.AddField(
            model_name='mentoriaaovivo',
            name='turma',
            field=models.ForeignKey(blank=True, help_text="Só usado quando o público é 'Uma turma inteira'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorias', to='cursos.turma'),
        ),
    ]
