# Generated by Django 4.2.30 on 2026-08-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0021_mentoriaaovivo_alunos_mentoriaaovivo_publico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaosite',
            name='hero_badge_texto',
            field=models.CharField(blank=True, default='Turmas abertas', help_text='Deixe em branco para ocultar o selo.', max_length=50, verbose_name='Selo acima do título (hero)'),
        ),
    ]
