# Generated by Django 6.0.7 on 2026-07-11 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='deve_trocar_senha',
            field=models.BooleanField(default=False, verbose_name='precisa trocar a senha no próximo acesso'),
        ),
    ]
