# Generated by Django 6.0.7 on 2026-07-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('destinatario', models.CharField(max_length=200)),
                ('assunto', models.CharField(blank=True, max_length=200)),
                ('mensagem', models.TextField()),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificação enviada',
                'verbose_name_plural': 'Notificações enviadas',
                'ordering': ['-enviado_em'],
            },
        ),
    ]
