# Generated by Django 6.0.7 on 2026-08-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('mock', 'Modo teste (só registra, não envia nada de verdade)'), ('smtp', 'Email real (SMTP — Gmail/Google Workspace)')], default='mock', max_length=20)),
                ('email_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=255, verbose_name='servidor SMTP')),
                ('email_port', models.PositiveIntegerField(default=587, verbose_name='porta SMTP')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='usar TLS')),
                ('email_host_user', models.EmailField(blank=True, help_text='A conta Gmail/Google Workspace que vai enviar.', max_length=254, verbose_name='email remetente')),
                ('email_host_password', models.CharField(blank=True, help_text='Senha de app do Google (16 caracteres) — não é a senha normal da conta. Gera em myaccount.google.com/apppasswords (precisa de verificação em 2 etapas ativada).', max_length=255, verbose_name='senha de app')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de notificações',
                'verbose_name_plural': 'Configuração de notificações',
            },
        ),
    ]
