# Generated by Django 6.0.7 on 2026-08-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0002_configuracaonotificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='site_url',
            field=models.URLField(default='https://rscentraldoscursos.com.br', help_text='Endereço base usado nos links dos emails enviados ao aluno. Ex.: https://rscentraldoscursos.com.br (sem barra no fim).', verbose_name='URL do site (Portal do Aluno)'),
        ),
    ]
