# Generated by Django 6.0.7 on 2026-08-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_configuracaonotificacao_site_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=50, unique=True)),
                ('assunto', models.CharField(blank=True, max_length=255)),
                ('corpo', models.TextField(blank=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modelo de email',
                'verbose_name_plural': 'Modelos de email',
            },
        ),
    ]
