# Generated by Django 6.0.7 on 2026-08-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0004_modeloemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='whatsapp_admin',
            field=models.CharField(blank=True, help_text='Número que recebe os avisos de admin (matrícula, contato). Com DDD, ex.: 11998887777.', max_length=20, verbose_name='WhatsApp do admin'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='whatsapp_backend',
            field=models.CharField(choices=[('mock', 'Modo teste (não envia WhatsApp de verdade)'), ('zapi', 'WhatsApp real (Z-API)')], default='mock', max_length=20, verbose_name='envio de WhatsApp'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='zap_codigo',
            field=models.BooleanField(default=False, verbose_name='WhatsApp: código de recuperação'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='zap_comunicado',
            field=models.BooleanField(default=False, verbose_name='WhatsApp: comunicado em massa (cuidado: risco de bloqueio)'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='zap_contato',
            field=models.BooleanField(default=False, verbose_name='WhatsApp: contato/orçamento (admin)'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='zap_credenciais',
            field=models.BooleanField(default=False, verbose_name='WhatsApp: boas-vindas/credenciais'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='zap_ingresso_turma',
            field=models.BooleanField(default=False, verbose_name='WhatsApp: ingresso em turma'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='zap_matricula',
            field=models.BooleanField(default=False, verbose_name='WhatsApp: matrícula confirmada'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='zap_mentoria',
            field=models.BooleanField(default=False, verbose_name='WhatsApp: aviso de mentoria'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='zap_turma_aberta',
            field=models.BooleanField(default=False, verbose_name='WhatsApp: turma nova (interessados)'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='zapi_client_token',
            field=models.CharField(blank=True, help_text='Account Security Token do painel Z-API (se ativado).', max_length=200, verbose_name='Z-API client-token (segurança da conta)'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='zapi_instance_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Z-API instance id'),
        ),
        migrations.AddField(
            model_name='configuracaonotificacao',
            name='zapi_token',
            field=models.CharField(blank=True, max_length=200, verbose_name='Z-API token'),
        ),
    ]
