# Generated by Django 6.0.7 on 2026-08-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0005_configuracaonotificacao_whatsapp_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='zapi_client_token',
            field=models.CharField(blank=True, help_text="No painel Z-API, menu Segurança → 'Account Security Token'. É diferente do token da instância. Se não ativou a segurança, deixe vazio.", max_length=200, verbose_name='Client-Token (Account Security Token)'),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='zapi_instance_id',
            field=models.CharField(blank=True, help_text="No painel Z-API: 'ID da instância'. Ex.: 3F7BA3E0486D6127AD3ED27B159993B4", max_length=100, verbose_name='ID da instância'),
        ),
        migrations.AlterField(
            model_name='configuracaonotificacao',
            name='zapi_token',
            field=models.CharField(blank=True, help_text="No painel Z-API: 'Token da instância'. Ex.: A9AECD6E973E3C1F38BDCBD9", max_length=200, verbose_name='Token da instância'),
        ),
    ]
