# Generated by Django 4.2.30 on 2026-08-11 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0017_turma_informacoes_acesso_turma_link_grupo_whatsapp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matriculas', '0002_aulaconcluida_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteresseTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('notificado_em', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_turma', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesses_turma', to='cursos.curso')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('aluno', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='InscricaoTurma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_turma', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='cursos.turma')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('aluno', 'turma')},
            },
        ),
    ]
